import {useEffect,useRef,useState} from 'react';
import OceanMap from './OceanMap';
import './App.css';
const DEPTHS=[0,5,10,20,30,50,75,100,125,150,200,300,500,700,1000];
const TABS=[['dashboard','Home / Map'],['profile','Depth Profile'],['inversion','Model vs Reality'],['metrics','Metrics'],['methodology','Methodology'],['ai','AI Desk']];
const names={arabian_sea:'Arabian Sea',bay_of_bengal:'Bay of Bengal / eastern partition',glorys:'GLORYS reanalysis',independent_argo:'Independent ARGO'};
const fmt=(x,n=3)=>typeof x==='number'&&Number.isFinite(x)?x.toFixed(n):'—';
// Static mode: served from GitHub Pages (no backend); dynamic mode: local/Render server
const RENDER_BASE=import.meta.env.VITE_RENDER_API_BASE||'';
const STATIC_MODE=import.meta.env.VITE_STATIC_MODE==='true';
function apiUrl(path){
  if(STATIC_MODE){
    if(path==='/api/coverage')return'/data/coverage.json';
    if(path.startsWith('/api/regime-metrics'))return'/data/metrics.json';
    if(path.startsWith('/api/inversion-case'))return'/data/cases.json';
    if(path.startsWith('/api/profile'))return`${RENDER_BASE}/api/profile${path.includes('?')?path.slice(path.indexOf('?')):''}`;
  }
  return path;
}
async function request(path,options={}){const url=apiUrl(path);let r;try{r=await fetch(url,{...options,signal:options.signal||AbortSignal.timeout(path==='/api/ai'?100000:55000)});}catch(e){if(e.name==='AbortError')throw e;throw Error('The service could not be reached in time. Please retry.',{cause:e});}let d;try{d=await r.json();}catch{throw Error('The service returned an unreadable response. Please retry.');}if(!r.ok)throw Error(d.error||`Request failed (${r.status}). Please retry.`);return d;}
function useData(path){const [state,set]=useState({loading:true,data:null,error:null});const[attempt,retry]=useState(0);useEffect(()=>{const c=new AbortController();request(path,{signal:c.signal}).then(data=>set({loading:false,data,error:null})).catch(e=>{if(e.name!=='AbortError')set({loading:false,data:null,error:e.message});});return()=>c.abort();},[path,attempt]);return {...state,retry:()=>{set(s=>({...s,loading:true,error:null}));retry(x=>x+1);}};}
function Panel({title,children,className=''}){return <section className={`panel ${className}`}><h2 className="panel-title">{title}</h2><div className="panel-body">{children}</div></section>;}
function State({loading,error,retry}){return loading?<p role="status" className="notice">Loading real data… The profile service may need time to wake up.</p>:error?<div role="alert" className="notice error">{error} <button onClick={retry}>Retry</button></div>:null;}
function Chart({series,maxDepth=1000,uncertainty}){
 const values=series.flatMap(s=>s.values.filter(x=>typeof x==='number'&&Number.isFinite(x)));if(!values.length)return <p className="notice">No measured or reconstructed values are available for this selection.</p>;
 const min=Math.floor(Math.min(...values)-2),max=Math.ceil(Math.max(...values)+2),x=t=>65+(t-min)/(max-min)*465,y=d=>35+d/maxDepth*390;
 return <svg className="profile-chart" viewBox="0 0 600 475" role="img" aria-label={`Temperature versus depth from 0 to ${maxDepth} metres. Missing depths are gaps.`}>
  {[0,1,2,3,4,5].map(i=>{const t=min+(max-min)*i/5;return <g key={i}><line x1={x(t)} x2={x(t)} y1="35" y2="425" stroke="#e2e8f0"/><text x={x(t)} y="450" textAnchor="middle">{t.toFixed(1)}</text></g>;})}
  {DEPTHS.filter(d=>d<=maxDepth&&(maxDepth<=50||[0,100,200,300,500,700,1000].includes(d))).map(d=><g key={d}><line x1="65" x2="530" y1={y(d)} y2={y(d)} stroke="#e2e8f0"/><text x="52" y={y(d)+4} textAnchor="end">{d}</text></g>)}
  <text x="290" y="473" textAnchor="middle">Temperature (°C)</text><text transform="translate(17,250) rotate(-90)" textAnchor="middle">Depth (m)</text>
  {series.map(s=><g key={s.name}>{s.values.map((v,i)=>{if(v===null||v===undefined||DEPTHS[i]>maxDepth)return null;const prev=s.values[i-1];return <g key={i}>{i>0&&prev!==null&&prev!==undefined&&<line x1={x(prev)} y1={y(DEPTHS[i-1])} x2={x(v)} y2={y(DEPTHS[i])} stroke={s.color} strokeWidth="2.5"/>}{uncertainty&&s.name==='Model'&&Number.isFinite(uncertainty[i])&&<line x1={x(v-uncertainty[i])} x2={x(v+uncertainty[i])} y1={y(DEPTHS[i])} y2={y(DEPTHS[i])} stroke={s.color} strokeWidth="6" opacity="0.2"/>}<circle cx={x(v)} cy={y(DEPTHS[i])} r="3" fill={s.color}><title>{s.name}: {DEPTHS[i]} m, {fmt(v)} °C</title></circle></g>;})}</g>)}
 </svg>;
}
function download(rows,name){const keys=Object.keys(rows[0]||{});const csv=[keys.join(','),...rows.map(r=>keys.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
function Profile({state}){const p=state.data;return <><State {...state}/>{p&&<><p className="notice">{p.obs_date} · Matched grid: {p.lat.toFixed(3)}°N, {p.lon.toFixed(3)}°E · {p.matching.distance_km.toFixed(2)} km from request. {names[p.regime]}.</p><div className="two-col"><div><Chart series={[{name:'Model',color:'#005A9C',values:p.temperature_c}]} uncertainty={p.uncertainty_c}/><p className="muted">Horizontal bars: ±1 model uncertainty scale, uncalibrated. These are not confidence intervals. Gaps remain missing.</p></div><div className="table-scroll"><table><thead><tr><th>Depth (m)</th><th>Model (°C)</th><th>Scale (°C)</th></tr></thead><tbody>{DEPTHS.map((d,i)=><tr key={d}><td>{d}</td><td>{fmt(p.temperature_c[i])}</td><td>{p.temperature_c[i]===null?'—':fmt(p.uncertainty_c[i])}</td></tr>)}</tbody></table><button className="secondary" onClick={()=>download(DEPTHS.map((d,i)=>({depth_m:d,temperature_c:p.temperature_c[i],uncertainty_c:p.temperature_c[i]===null?null:p.uncertainty_c[i]})),'oceanembed-profile.csv')}>Download profile CSV</button></div></div></>}</>;}
function Methodology(){return <div className="method-grid">
 <Panel title="Satellite inputs → stored temperature profiles"><ol><li>The supplied cube spans 1 January–30 June 2023 on a daily 100 × 240 grid at 0.25°. It contains SST, SSS, SSH, geostrophic and ageostrophic currents, and wind components.</li><li>The notebook stacks seven days of nine input channels. A CNN encoder receives a longitude-based soft regime gate, with a transition around 78°E.</li><li>Dense layers mix features across the 15 depths. The inspected decoder is not a Transformer or self-attention layer.</li><li>The temperature head predicts anomalies; stored climatology is added back. A separate head estimates a model uncertainty scale.</li><li>This demo serves precomputed profiles from the existing Render API and Aiven database. It does not run satellite ingestion or model inference on request.</li></ol></Panel>
 <Panel title="Evaluation and scientific limitations"><ul><li>Exports cover 2 May–30 June 2023. The notebook separates this period from weight fitting, but sampled stored climatology matches a fit using the full time series, including it; results are provisional, not leakage-free validation.</li><li>Missing training targets were replaced by zero and included in ordinary MSE. A corrected masked objective and training-only preprocessing are needed before new scientific claims.</li><li>The sign-change penalty uses a non-differentiable sign operation on anomalies. It is not a validated hydrostatic or density constraint.</li><li>Temperature-only MLD/SLD proxies produced an all-zero BLT proxy in recorded output. Density-based barrier-layer thickness is unavailable.</li><li>Uncertainty calibration has not been established. The UI shows an uncalibrated scale, never a calibrated confidence interval.</li><li>No final model checkpoint or acquisition/preprocessing source was supplied. The local cube also lacks the notebook’s required ocean_mask variable. Exact checkpoint provenance and a fresh untouched test period remain unresolved.</li></ul></Panel>
 <Panel title="How to read the comparisons"><p>GLORYS is the model’s reanalysis target. Independent ARGO is a separate gridded comparison; keep both results separate. Sample counts refer to matched grid values and do not establish statistically independent observations.</p><p>Region controls use the export’s longitude partition: west of 78°E and east of 78°E. These are not precise geographic basin masks.</p><p>The two selected inversion cases are at 5.125°N, 99.125°E in the eastern/Andaman area. They contain model and GLORYS values only over 0–50 m; ARGO is missing. Local case RMSE is selected performance, not aggregate model skill.</p></Panel>
 <Panel title="Coverage and unavailable products"><p>Use the available date list and cyan map points. Requests match the nearest supported grid cell within 25 km; the actual match and distance are shown.</p><p>Missing values are preserved. Satellite layer visualization, live inference, density diagnostics, cyclone heat potential and live float telemetry are unavailable in this prototype.</p><p>Sources: supplied reconstruction, regional metrics and inversion-case CSV exports; OceanEmbed_Training.ipynb; oceanembed_cube.nc. Data and architecture claims were checked against these files rather than historical status reports.</p><a href="/api/coverage" target="_blank" rel="noreferrer">View coverage metadata</a></Panel>
 </div>;}
export default function App(){
 const [tab,setTab]=useState(()=>TABS.some(t=>t[0]===location.hash.slice(1))?location.hash.slice(1):'dashboard');
 const coverage=useData('/api/coverage'),metrics=useData('/api/regime-metrics'),cases=useData('/api/inversion-case');
 const[date,setDate]=useState('2023-05-02'),[lat,setLat]=useState('14.375'),[lon,setLon]=useState('88.125'),[sector,setSector]=useState('all');
 const[profile,setProfile]=useState({data:null,loading:false,error:null});const profileController=useRef(null);
 const[region,setRegion]=useState('bay_of_bengal'),[target,setTarget]=useState('glorys'),[caseId,setCaseId]=useState(''),[maxDepth,setMaxDepth]=useState(50);
 const[input,setInput]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false);const[font,setFont]=useState(16),[contrast,setContrast]=useState(false);
 useEffect(()=>{const change=()=>setTab(TABS.some(t=>t[0]===location.hash.slice(1))?location.hash.slice(1):'dashboard');window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 function navigate(t){location.hash=t;setTab(t);}
 async function loadProfile(d=date,a=lat,b=lon){profileController.current?.abort();const controller=new AbortController();profileController.current=controller;setProfile({loading:true,data:null,error:null});try{const data=await request(`/api/profile?${new URLSearchParams({date:d,lat:a,lon:b})}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(55000)])});if(!controller.signal.aborted)setProfile({loading:false,data,error:null});}catch(e){if(!controller.signal.aborted)setProfile({loading:false,data:null,error:e.message});}}
 function chooseDate(v){setDate(v);loadProfile(v);}
 function chooseLocation(a,b){setLat(Number(a).toFixed(3));setLon(Number(b).toFixed(3));loadProfile(date,a,b);}
 function changeCoordinate(setter,value){profileController.current?.abort();setter(value);setProfile({loading:false,data:null,error:null});}
 const rows=(metrics.data||[]).filter(r=>r.regime===region&&r.validation_target===target);
 const caseKeys=[...new Set((cases.data||[]).map(r=>`${r.obs_date}|${r.lat}|${r.lon}`))];const selected=caseKeys.includes(caseId)?caseId:caseKeys[0];const caseRows=(cases.data||[]).filter(r=>`${r.obs_date}|${r.lat}|${r.lon}`===selected);
 const caseSeries=[['model_temp','Model','#005A9C'],['glorys_temp','GLORYS','#d97706'],['raw_argo_temp','ARGO','#059669']].map(([key,name,color])=>({name,color,values:DEPTHS.map(d=>caseRows.find(r=>r.depth_m===d)?.[key]??null)}));
 const pairs=caseRows.filter(r=>r.depth_m<=50&&r.model_temp!==null&&r.glorys_temp!==null);const localRmse=pairs.length?Math.sqrt(pairs.reduce((s,r)=>s+(r.model_temp-r.glorys_temp)**2,0)/pairs.length):null;
 async function ask(question=input){if(busy||!question.trim())return;setInput('');setBusy(true);setMessages(m=>[...m,{role:'user',text:question}]);try{const d=await request('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:question,context:{date,lat:Number(lat),lon:Number(lon)}})});setMessages(m=>[...m,{role:'assistant',text:d.answer,tools:d.tools}]);}catch(e){setMessages(m=>[...m,{role:'error',text:e.message,retry:question}]);}finally{setBusy(false);}}
 const presets=[`Get the temperature profile on ${date} at ${lat} N, ${lon} E.`,`Get regional metrics for ${names[region]} against ${names[target]}, including RMSE at 100 m.`,`Get the inversion cases and explain the model versus GLORYS values over 0–50 m and missing ARGO.`];
 return <div className={`app-shell ${contrast?'high-contrast':''}`} style={{fontSize:font}}>
  <header className="access-bar"><span>Team RGIPT · Smart India Hackathon 2026 · PS 26066</span><div><button aria-label="Decrease text size" onClick={()=>setFont(x=>Math.max(14,x-1))}>A−</button><button aria-label="Reset text size" onClick={()=>setFont(16)}>A</button><button aria-label="Increase text size" onClick={()=>setFont(x=>Math.min(20,x+1))}>A+</button><button onClick={()=>setContrast(x=>!x)} aria-pressed={contrast}>Contrast</button></div></header>
  <div className="masthead"><div className="brand-mark" aria-hidden="true">≈</div><div><h1>OceanEmbed <span className="badge">PROTOTYPE · SIH 2026</span></h1><p>Satellite-to-Subsurface 3D Ocean Temperature Reconstruction Framework</p><small>Built for PS 26066 · INCOIS / Ministry of Earth Sciences challenge</small></div><div className="team-label">Team RGIPT<br/><small>Research demonstration</small></div></div>
  <div className="status-strip">PRECOMPUTED OUTPUTS <span>2 May–30 June 2023 · Provisional evaluation · Uncertainty is uncalibrated</span></div>
  <nav aria-label="Main navigation">{TABS.map(([id,label])=><button key={id} onClick={()=>navigate(id)} className={tab===id?'tab-active':''} aria-current={tab===id?'page':undefined}>{label}</button>)}</nav>
  <div className="selection-bar"><strong>North Indian Ocean · 0.25° grid</strong><label>Available date <select value={date} onChange={e=>chooseDate(e.target.value)} disabled={!coverage.data}>{(coverage.data?.dates||[date]).map(d=><option key={d}>{d}</option>)}</select></label><span>15 standard depths · 0–1000 m</span></div>
  <main>
   {tab==='dashboard'&&<><div className="hero-grid"><section className="ocean-hero"><span className="eyebrow">SATELLITE TO SUBSURFACE</span><h2>Reconstructing what satellites cannot see:<br/><span>the ocean beneath the surface.</span></h2><p>Explore the supplied model’s stored temperature profiles, regional evaluation, and selected inversion cases across the North Indian Ocean.</p><div className="hero-stats"><div><strong>{coverage.data?coverage.data.profiles.toLocaleString():'—'}</strong><small>PRECOMPUTED PROFILES</small></div><div><strong>{coverage.data?coverage.data.points.length.toLocaleString():'—'}</strong><small>SUPPORTED GRID CELLS / DAY</small></div><div><strong>15</strong><small>STANDARD DEPTH POSITIONS</small></div></div></section><Panel title="Explore the demonstration"><p>Select an available date, then click a cyan ocean grid point. The matching cell and real profile will appear below.</p><p className="muted">This is a research prototype serving stored outputs. No live satellite ingestion or reconstruction runs in the browser.</p><button onClick={()=>navigate('methodology')}>Pipeline & limitations</button></Panel></div>
   <State {...coverage}/><div className="map-layout"><Panel title="North Indian Ocean coverage" className="map-panel"><div className="control-row"><label>Map region <select value={sector} onChange={e=>setSector(e.target.value)}><option value="all">All supported points</option><option value="arabian_sea">Arabian Sea · west of 78°E</option><option value="bay_of_bengal">Eastern partition · 78°E and east</option></select></label><span className="muted">Cyan: available model grid · Orange: request</span></div><div className="map-wrap"><OceanMap points={coverage.data?.points} lat={lat} lon={lon} region={sector} onSelect={chooseLocation}/></div><p className="muted">Nearest supported point within 25 km. The basemap is geographic context; it is not a temperature raster.</p></Panel><Panel title="Selected ocean location"><form onSubmit={e=>{e.preventDefault();loadProfile();}}><label>Latitude (°N)<input required type="number" step="any" min="5" max="30" value={lat} onChange={e=>changeCoordinate(setLat,e.target.value)}/></label><label>Longitude (°E)<input required type="number" step="any" min="45" max="105" value={lon} onChange={e=>changeCoordinate(setLon,e.target.value)}/></label><button type="submit">Retrieve profile</button></form><div className="quick-points"><button className="secondary" onClick={()=>chooseLocation(14.375,88.125)}>Central Bay of Bengal</button><button className="secondary" onClick={()=>chooseLocation(15.125,68.125)}>Arabian Sea</button><button className="secondary" onClick={()=>chooseLocation(5.125,99.125)}>Eastern case location</button></div><p className="muted">These are grid locations, not named ARGO floats. Unsupported land or distant requests return an unavailable state.</p></Panel></div><Panel title="Selected depth profile">{!profile.loading&&!profile.data&&!profile.error&&<p className="notice">Choose a location above to retrieve its profile.</p>}<Profile state={{...profile,retry:()=>loadProfile()}}/></Panel></>}
   {tab==='profile'&&<Panel title="Depth Profile"><form className="control-row" onSubmit={e=>{e.preventDefault();loadProfile();}}><label>Latitude (°N)<input required type="number" min="5" max="30" step="any" value={lat} onChange={e=>changeCoordinate(setLat,e.target.value)}/></label><label>Longitude (°E)<input required type="number" min="45" max="105" step="any" value={lon} onChange={e=>changeCoordinate(setLon,e.target.value)}/></label><button>Retrieve profile</button></form>{!profile.data&&!profile.loading&&!profile.error&&<p className="notice">Select coordinates and retrieve the profile for {date}.</p>}<Profile state={{...profile,retry:()=>loadProfile()}}/></Panel>}
   {tab==='inversion'&&<Panel title="Model vs Reality · selected inversion cases"><State {...cases}/>{caseRows.length>0&&<><div className="control-row"><label>Case <select value={selected} onChange={e=>setCaseId(e.target.value)}>{caseKeys.map(k=><option key={k} value={k}>{k.replaceAll('|',' · ')}</option>)}</select></label><label>Depth range <select value={maxDepth} onChange={e=>setMaxDepth(Number(e.target.value))}><option value={50}>0–50 m · populated depths</option><option value={1000}>0–1000 m · show missing coverage</option></select></label></div><p className="notice">Selected local RMSE vs GLORYS: <strong>{fmt(localRmse)} °C</strong> over {pairs.length} depths, 0–50 m. Cases were chosen for low local error; this does not represent aggregate skill.</p><p>Eastern / Andaman-area grid: 5.125°N, 99.125°E. ARGO is unavailable in both cases. Depths below 50 m remain missing.</p><div className="legend">{caseSeries.map(s=><span key={s.name} style={{color:s.color}}>● {s.name}{s.name==='ARGO'?' · unavailable':''}</span>)}</div><div className="two-col"><Chart series={caseSeries} maxDepth={maxDepth}/><div className="table-scroll"><table><thead><tr><th>Depth (m)</th><th>Model (°C)</th><th>GLORYS (°C)</th><th>ARGO (°C)</th></tr></thead><tbody>{caseRows.map(r=><tr key={r.depth_m}><td>{r.depth_m}</td><td>{fmt(r.model_temp)}</td><td>{fmt(r.glorys_temp)}</td><td>{fmt(r.raw_argo_temp)}</td></tr>)}</tbody></table></div></div></>}{!cases.loading&&!cases.error&&!caseRows.length&&<p className="notice">No inversion-case data available.</p>}</Panel>}
   {tab==='metrics'&&<Panel title="Regional validation metrics"><div className="control-row"><label>Region <select value={region} onChange={e=>setRegion(e.target.value)}>{Object.entries(names).slice(0,2).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Validation target <select value={target} onChange={e=>setTarget(e.target.value)}><option value="glorys">GLORYS reanalysis</option><option value="independent_argo">Independent ARGO</option></select></label><button disabled={!rows.length} onClick={()=>download(rows,`oceanembed-${region}-${target}.csv`)}>Download metrics CSV</button></div><p className="notice">Provisional exported evaluation · May–June 2023. GLORYS and independent ARGO are separate comparisons. Preprocessing and target masking issues limit scientific interpretation.</p><State {...metrics}/>{rows.length>0?<div className="table-scroll"><table><thead><tr><th>Depth (m)</th><th>RMSE (°C)</th><th>Bias (°C)</th><th>Correlation (r)</th><th>Matched grid values</th></tr></thead><tbody>{DEPTHS.map(d=>{const r=rows.find(x=>x.depth_m===d);return <tr key={d}><td>{d}</td><td>{fmt(r?.rmse_c)}</td><td>{fmt(r?.bias_c)}</td><td>{fmt(r?.correlation)}</td><td>{r?.n_points.toLocaleString()||'Unavailable at surface'}</td></tr>;})}</tbody></table></div>:!metrics.loading&&!metrics.error&&<p className="notice">No metrics for this selection.</p>}<p className="muted">No ARGO surface metric was exported. Region labels follow a 78°E longitude split. Correlation is not an R² score or a percentage accuracy.</p></Panel>}
   {tab==='methodology'&&<Methodology/>}
   {tab==='ai'&&<Panel title="AI Desk · Gemini scientific narrator"><p>Ask Gemini to retrieve the actual stored outputs. Numerical answers use server-side data tools; missing coverage and provider errors are reported explicitly.</p><div className="control-row presets">{presets.map((p,i)=><button key={p} disabled={busy} className="secondary" onClick={()=>ask(p)}>{['Ask about profile','Ask about metrics','Ask about inversion cases'][i]}</button>)}</div><div className="chat-log" aria-live="polite">{!messages.length&&<p className="notice">Select a question above or ask your own. Each question uses the selected date and location.</p>}{messages.map((m,i)=><article key={i} className={`message ${m.role}`}><strong>{m.role==='user'?'You':m.role==='error'?'AI Desk error':'OceanEmbed Assistant'}</strong><p>{m.text}</p>{m.tools&&<details><summary>Retrieved data tools ({m.tools.length})</summary><ul>{m.tools.map((t,j)=><li key={j}>{t.name} · {t.status}</li>)}</ul></details>}{m.retry&&<button disabled={busy} onClick={()=>ask(m.retry)}>Retry question</button>}</article>)}{busy&&<p role="status" className="notice">Gemini is retrieving data and preparing an answer…</p>}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();ask();}}><label htmlFor="question">Your question</label><textarea id="question" required maxLength={2000} rows={3} value={input} onChange={e=>setInput(e.target.value)} placeholder="Compare GLORYS and ARGO RMSE at 100 m in the Arabian Sea."/><button disabled={busy||!input.trim()}>Ask Gemini</button></form><p className="muted">Up to 6 questions per minute per IP and 6 tool calls per question. Each question is independent; include any needed context.</p></Panel>}
  </main><footer>OceanEmbed · Team RGIPT · SIH 2026 prototype. Not an official Government of India product. Precomputed research outputs; not for operational forecasting.</footer>
 </div>;
}
